/**
 * Placeholder IDL type for the Magic Chess program.
 *
 * This is a minimal type stub. The full IDL is generated by `anchor build`
 * and can be found at `program/target/idl/speed_chess.json`.
 *
 * Regenerate with: anchor build && anchor idl type
 */

export type MagicChess = {
  address: "5Ro6jsg6ov1VmEQ7Un5NAaydyfpUKDvABCK5CE5qN5E6";
  metadata: {
    name: "magicChess";
    version: "0.1.0";
    spec: "0.1.0";
    description: "On-chain chess engine with wagering";
  };
  instructions: [
    {
      name: "initializeMatch";
      accounts: [
        { name: "chessMatch"; writable: true; pda: object };
        { name: "playerSigner"; writable: true; signer: true };
        { name: "bettingTokenMintAccount" };
        { name: "playerTokenAccount"; writable: true };
        { name: "matchEscrowTokenAccount"; writable: true; pda: object };
        { name: "tokenProgram"; address: string };
        { name: "systemProgram"; address: string };
      ];
      args: [
        { name: "matchIdArg"; type: "string" },
        { name: "betAmountArg"; type: "u64" },
        { name: "moveTimeoutDurationArg"; type: "i64" },
        { name: "platformFeeBasisPointsArg"; type: "u16" },
        { name: "platformFeeWalletArg"; type: "pubkey" },
      ];
    },
    {
      name: "joinMatch";
      accounts: [
        { name: "chessMatch"; writable: true; pda: object };
        { name: "playerTwoSigner"; writable: true; signer: true };
        { name: "playerTokenAccount"; writable: true };
        { name: "matchEscrowTokenAccount"; writable: true; pda: object };
        { name: "tokenProgram"; address: string };
        { name: "systemProgram"; address: string };
      ];
      args: [{ name: "betAmountArg"; type: "u64" }];
    },
    {
      name: "makeMove";
      accounts: [
        { name: "chessMatch"; writable: true; pda: object };
        { name: "player"; writable: true; signer: true };
      ];
      args: [{ name: "args"; type: { defined: { name: "makeMoveArgs" } } }];
    },
    {
      name: "resignGame";
      accounts: [
        { name: "chessMatch"; writable: true; pda: object };
        { name: "playerSigner"; writable: true; signer: true };
      ];
      args: [];
    },
    {
      name: "claimTimeoutWin";
      accounts: [
        { name: "chessMatch"; writable: true; pda: object };
        { name: "claimerSigner"; writable: true; signer: true };
      ];
      args: [];
    },
    {
      name: "processMatchSettlement";
      accounts: [
        { name: "chessMatch"; writable: true; pda: object };
        { name: "matchEscrowTokenAccount"; writable: true; pda: object };
        { name: "playerOneAta"; writable: true };
        { name: "playerTwoAta"; writable: true };
        { name: "platformFeeAta"; writable: true };
        { name: "tokenProgram"; address: string };
      ];
      args: [];
    },
  ];
  accounts: [{ name: "chessMatch" }];
  events: [
    { name: "matchCreatedEvent" },
    { name: "playerJoinedEvent" },
    { name: "moveMadeEvent" },
    { name: "gameEndedEvent" },
    { name: "payoutEvent" },
    { name: "drawPayoutEvent" },
  ];
  errors: object[];
  types: object[];
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  [key: string]: any;
};
